services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_test

  web:
    build:
      context: .
      dockerfile: Dockerfile
      entrypoint: ""
    environment:
      RAILS_ENV: test
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: blog_test
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "chmod +x ./test.sh && ./test.sh"
