name: Run tests with Docker Compose
on:
  push:
    branches:
      - add-test-docker

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        id: run_tests
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit
      - name: Upload test logs
        if: failure() && steps.run_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: rspec.log
